[build]
target-dir = "target"

[profile.release]
lto = true
opt-level = 3
strip = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"

[target.aarch64-unknown-linux-gnu]
linker = "clang"

[target.x86_64-apple-darwin]
linker = "clang"

[target.aarch64-apple-darwin]
linker = "clang"

[target.x86_64-pc-windows-msvc]
linker = "clang"
